services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: near-store-price-checker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: apps/backend
    container_name: backend
    command: pnpm run start:dev
    ports:
      - "8001:8001"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/near-store-price-checker_db"
    depends_on:
      - postgres

  frontend:
    build:
      context: apps/frontend
    container_name: frontend
    command: pnpm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data: