services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: barcode_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend
    command: pnpm run start:dev
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/barcode_db"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    command: pnpm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  postgres_data: